version: '3.3'
services:
  sonarqube:
    image: sonarqube:8.5.1-community
    container_name: sonarqube2_alfred
    hostname: sonarqube2
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
    volumes:
      - /opt/sonar/logs:/opt/sonarqube/logs
      - /opt/sonar/data:/opt/sonarqube/data
      - /opt/sonar/extensions:/opt/sonarqube/extensions
    restart: always

  db:
    image: postgres:13.1
    container_name: db
    hostname: db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - pg_db:/var/lib/postgresql
      - pg_data:/var/lib/postgresql/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
   pg_db:
     driver: local
   pg_data:
     driver: local 
  
